# Playoff Season Multi Linear Regression

This is the algortihm which is there to predict Currys 3 point shooting percentage based on multiple features (playoffs). Therefore this wont be a linear regression but instead a multi linear regression due to the multiple independent variables. This code below is there to incorperate the ML tool and predict the shooting percentage. It is important to have the csv file, "playoff_curry_data_set.csv" this can be found on https://drive.google.com/open?id=1o19nc_PrgClDHhrHgbxvjnE4J7rgbyuv make sure this code and the csv file are in the same directory, include them in the same file together. 
Developer: S. Singh

In [79]:
x1 = float(input("Enter a integer, for the season starting from 2015-16 as being 1:  "))
x2 = float(input("Enter the minutes Curry played that game:  "))
x3 = float(input("Enter the total points Curry had that game:  "))
x4 = float(input("Enter the Age Curry is playing the game at, his current age 2019-2020 is 32:  "))
x5 = float(input("Enter a integer, for the number of All-Star teamates Curry had playing along side him that game:  "))

Enter a integer, for the season starting from 2015-16 as being 1:   4
Enter the minutes Curry played that game:   30
Enter the total points Curry had that game:   40
Enter the Age Curry is playing the game at, his current age 2019-2020 is 32:   31
Enter a integer, for the number of All-Star teamates Curry had playing along side him that game:   3


In [80]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [81]:
df = pd.read_csv("playoff_curry_data_set.csv", delimiter=';')
df

S  MIN  TP  AGE  APP  P3P
0   4   37  24   31    3  400
1   4   44  25   31    3  273
2   4   37  36   31    3  375
3   4   43  47   31    2  429
4   3   27  28   30    3  500
5   3   34  16   30    3  125
6   3   44  27   30    3  357
7   3   38  33   30    3  529
8   2   30  37   29    3  636
9   2   38  23   29    3  625
10  2   32  29   29    3  667
11  2   36  32   29    3  364
12  1   20  24   28    2  714
13  1   39  19   28    2  273
14  1   37  40   28    2  313
15  1   35  30   28    2  462

In [82]:
reg = linear_model.LinearRegression()

In [83]:
reg.fit(df[['S','MIN','TP','AGE','APP']],df.P3P)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [84]:
df.columns

Index(['S', 'MIN', 'TP', 'AGE', 'APP', 'P3P'], dtype='object')

In [85]:
#this will display the coefficents of each of the independent variables, x1,x2,x3,x4,x5
reg.coef_

array([-18.8221527 , -14.07648422,   8.1078562 , -18.8221527 ,
       101.20854853])

In [86]:
#this is going to show the final "b" value in the equation for multi linear regression
reg.intercept_

1034.6221667614277

In [87]:
#the output is the final predicted 3-point value
reg.predict([[x1,x2,x3,x4,x5]])

array([581.49218941])

In [89]:
#the output is the final predicted 3-point percentage
reg.predict([[x1,x2,x3,x4,x5]])/10

array([58.14921894])

In [91]:
#the output is the final predicted 3-point decimal 
reg.predict([[x1,x2,x3,x4,x5]])/1000

array([0.58149219])

In [88]:
#this is the r^2 value 
reg.score(df[['S','MIN','TP','AGE','APP']],df.P3P)

0.4626564702557192

In [ ]:
The equation used for Muli Linear Regression
Y = (B1*X1)+(B2*X2)+(B3*X3)+(B4*X4)+(B5*X5) + B

In [92]:
sum = -18.8221527*x1+-14.07648422*x2+8.1078562*x3+-18.8221527*x4+101.20854853*x5+1034.6221667614277
sum

581.4921892514276